// Verifies the packer's generated-source certification (#351): a source
// whose directory manifest lists exactly its bytes is cooked, a source the
// manifest lists with other bytes (an interrupted generator publish) is
// refused, an unlisted neighbour and a directory without a manifest are
// cooked, and a torn or foreign manifest refuses everything it covers.

#include "generated_manifest.h"

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <string>

#include "engine/core/hash.h"

namespace {

constexpr const char *kDir = "generated_manifest_test_dir";

bool write_file(const std::string &path, const std::string &text) {
  FILE *file = nullptr;
#ifdef _WIN32
  if (fopen_s(&file, path.c_str(), "wb") != 0) {
    file = nullptr;
  }
#else
  file = std::fopen(path.c_str(), "wb");
#endif
  if (file == nullptr) {
    return false;
  }
  const bool ok = std::fwrite(text.data(), 1U, text.size(), file) == text.size();
  std::fclose(file);
  return ok;
}

std::uint64_t hash_of(const std::string &text) {
  std::uint64_t hash = engine::core::kFnv1a64Offset;
  for (const char c : text) {
    hash = engine::core::fnv1a_64_append(hash,
                                         static_cast<unsigned char>(c));
  }
  return hash;
}

std::string manifest_text(const std::string &name, std::size_t bytes,
                          std::uint64_t hash) {
  char buffer[256] = {};
  std::snprintf(buffer, sizeof(buffer),
                "{\"schema\":1,\"files\":{\"%s\":{\"bytes\":%zu,"
                "\"fnv1a64\":\"%016llx\"}}}",
                name.c_str(), bytes, static_cast<unsigned long long>(hash));
  return buffer;
}

bool certified(const std::string &path, std::uint64_t hash) {
  char message[512] = {};
  const bool ok =
      generated_source_certified(path.c_str(), hash, message, sizeof(message));
  if (!ok) {
    std::printf("  refused: %s\n", message);
  }
  return ok;
}

} // namespace

int main() {
  std::error_code ec{};
  std::filesystem::remove_all(kDir, ec);
  std::filesystem::create_directories(kDir, ec);
  const std::string dir = std::string(kDir) + "/";
  const std::string source = dir + "thing.gltf";
  const std::string neighbour = dir + "hand_made.gltf";
  const std::string manifest = dir + "generated.manifest";
  const std::string bytes = "generated bytes";
  const std::string otherBytes = "generated bytes, next generation";
  if (!write_file(source, bytes) || !write_file(neighbour, "by hand")) {
    return 1;
  }

  // No manifest: cooked.
  if (!certified(source, hash_of(bytes))) {
    return 2;
  }
  // Listed with exactly these bytes: cooked.
  if (!write_file(manifest, manifest_text("thing.gltf", bytes.size(),
                                          hash_of(bytes))) ||
      !certified(source, hash_of(bytes))) {
    return 3;
  }
  // Unlisted neighbour beside a manifest: cooked.
  if (!certified(neighbour, hash_of("by hand"))) {
    return 4;
  }
  // The file was replaced by a newer generation but the manifest was
  // not (interrupted publish): refused.
  if (!write_file(source, otherBytes) ||
      certified(source, hash_of(otherBytes))) {
    std::fprintf(stderr, "FAIL: a mixed generation was accepted\n");
    return 5;
  }
  // Same size, different bytes: still refused (hash decides).
  const std::string sameSize = "generated BYTES";
  if (!write_file(source, sameSize) || certified(source, hash_of(sameSize))) {
    return 6;
  }
  // Torn manifest: refused.
  if (!write_file(source, bytes) || !write_file(manifest, "{\"schema\":1,") ||
      certified(source, hash_of(bytes))) {
    return 7;
  }
  // Foreign schema: refused.
  if (!write_file(manifest, "{\"schema\":2,\"files\":{}}") ||
      certified(source, hash_of(bytes))) {
    return 8;
  }
  std::filesystem::remove_all(kDir, ec);
  std::puts("generated_manifest_test passed");
  return 0;
}
